language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
# command to run tests
before_script:
  - sudo apt-get install -y shunit2 cscope ctags
#- curl -o shunit2 'https://raw.githubusercontent.com/kward/shunit2/master/shunit2'
script:
  - export PYTHONIOENCODING=utf8
  - shunit2 test/test.sh
